### ISSUE TITLE
It's impossible to aquire ownership of incoming `MyData`

### ISSUE THREAD

**Issue by KuSpa** [CabbitStudios/bevy_spicy_networking#10]
Since `NetworkData` does not implement `Clone`, it is impossible to acquire ownership of `inner` as one has only access through EventReader::iter() which hides `e` behind a reference. Thus, `into_inner` cannot be called. 
```rust 
fn handle(mut incoming: EventReader<NetworkData<MyData>>){
    for e in incoming.iter(){ // e:&NetworkData<MyData>
        // I want to retrieve e (and use it elsewhere)
        let data: MyData = e.into_inner(); // errors: cannot move
        let data: MyData = e.inner; // errors: inner is private
    }
}
```

I would propose making `inner` public.

edit: What I want is to `clone` `inner` :)

**Comment by KuSpa** [comment]
Then I seem to have missed something :), Could you provide an example?^.^*

**Comment by KuSpa** [comment]
Never mind
```rust
let data:MyData = (e as &MyData).clone();
```
does the trick :+1:

**Comment by TheNeikos** [comment]
If you want to, you could implement `AsRef` for `NetworkData` instead of `Deref` (which is not a good impl in this case actually), as well as adding an `inner` method, which would allow you to borrow the data (and to which `AsRef` simply defers).
