### ISSUE TITLE
Cannot send message with String value

### ISSUE THREAD

**Issue by mjhouse** [CabbitStudios/bevy_spicy_networking#17]
I'm unable to receive messages through bevy_spicy_networking that contain strings- I've sent and received empty messages and messages with u8 values, and so far this issue only occurs with string messages ([video](https://www.youtube.com/watch?v=ECMlmbhMpBc)).

See [this issue](https://github.com/dtolnay/erased-serde/issues/47) that I submitted to erased-serde for error messages etc. I'm not sure if I've done something wrong, if this is an issue with bevy_spicy_networking or erased-serde.

If it's a bug it seems like a bad one. You can clone and build warfare-rs (at [this commit](https://github.com/mjhouse/warfare-rs/tree/fc45fbeebeef31ff67af8f1d607632233b1b3217)) if you need to reproduce. The messages are defined in [networking/messages.rs](https://github.com/mjhouse/warfare-rs/blob/fc45fbeebeef31ff67af8f1d607632233b1b3217/src/networking/messages.rs), and the actual send/receive code is in [systems/network.rs](https://github.com/mjhouse/warfare-rs/blob/fc45fbeebeef31ff67af8f1d607632233b1b3217/src/systems/network.rs).

(there are some dependencies to build warfare, check the readme)

**Comment by TheNeikos** [comment]
Huh, that is not intended of course! 

https://github.com/CabbitStudios/bevy_spicy_networking/blob/0aa35dc5d48cc2fb40359a93dd2bd49e9e816e08/examples/shared.rs#L20

The examples actually have something quite similar in them, could you try those out on your machine?

**Comment by mjhouse** [comment]
@TheNeikos Huh, that's weird. The example works.

**Comment by mjhouse** [comment]
Whatever the issue was, it appears to be resolved in [erased-serde 0.3.17](https://github.com/dtolnay/erased-serde/issues/47). I can't reproduce with that version.

**Comment by TheNeikos** [comment]
Alright, great!
